# Generated by Django 3.1.7 on 2021-03-29 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_p', models.CharField(max_length=30)),
                ('apellidos_p', models.CharField(max_length=30)),
                ('rut_p', models.CharField(max_length=10)),
                ('sexo_p', models.CharField(max_length=1)),
                ('telefono_p', models.CharField(max_length=12)),
                ('fecha_nac_p', models.DateField()),
                ('estado_p', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FichaM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_fhc_fm', models.IntegerField()),
                ('mes_fch_fm', models.IntegerField()),
                ('anio_fch_fm', models.IntegerField()),
                ('diagnostico_fm', models.TextField()),
                ('motivo_fm', models.TextField()),
                ('paciente_fm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.paciente')),
            ],
        ),
    ]
